apiVersion: v1
kind: Service
metadata:
  labels:
    app: webclient
  name: webclient
spec:
  selector:
    app: webclient
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    protocol: TCP
